/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

// TapData Documentation docs list
  TapData: [
        {
         type: 'category',
         label: '连接数据源',
         link: {type: 'doc', id: 'prerequisites/README'},
         items: [
                 'prerequisites/supported-databases',
                 {
                  type: 'category',
                  label: '数据仓库与数据湖',
                  link: {type: 'doc', id: 'prerequisites/warehouses-and-lake/README'},
                  items: [
                          'prerequisites/warehouses-and-lake/big-query',
                          'prerequisites/warehouses-and-lake/clickhouse',
                          'prerequisites/warehouses-and-lake/doris',
                          'prerequisites/warehouses-and-lake/gaussdb',
                          'prerequisites/warehouses-and-lake/greenplum',
                          'prerequisites/warehouses-and-lake/hudi',
                          'prerequisites/warehouses-and-lake/selectdb',
                          'prerequisites/warehouses-and-lake/tablestore',
                          'prerequisites/warehouses-and-lake/yashandb',
                         ]
                  },
                 {
                  type: 'category',
                  label: '自建数据库',
                  link: {type: 'doc', id: 'prerequisites/on-prem-databases/README'},
                  items: [
                          'prerequisites/on-prem-databases/dameng',
                          'prerequisites/on-prem-databases/elasticsearch',
                          'prerequisites/on-prem-databases/hive1',
                          'prerequisites/on-prem-databases/hive3',
                          'prerequisites/on-prem-databases/mariadb',
                          'prerequisites/on-prem-databases/mongodb',
                          'prerequisites/on-prem-databases/mongodb-below34',
                          'prerequisites/on-prem-databases/mongodb-atlas',
                          'prerequisites/on-prem-databases/mrs-hive3',
                          'prerequisites/on-prem-databases/mysql',
                          'prerequisites/on-prem-databases/mysql-pxc',
                          'prerequisites/on-prem-databases/oceanbase',
                          'prerequisites/on-prem-databases/opengauss',
                          'prerequisites/on-prem-databases/postgresql',
                          'prerequisites/on-prem-databases/redis',
                          'prerequisites/on-prem-databases/tdengine',
                          'prerequisites/on-prem-databases/tidb',
                          'prerequisites/on-prem-databases/vastbase',
                          ]
                  },
                  {
                   type: 'category',
                   label: '云数据库',
                   link: {type: 'doc', id: 'prerequisites/cloud-databases/README'},
                   items: [
                           'prerequisites/cloud-databases/aliyun-adb-mysql',
                           'prerequisites/cloud-databases/aliyun-adb-postgresql',
                           'prerequisites/cloud-databases/aliyun-mongodb',
                           'prerequisites/cloud-databases/aliyun-rds-for-mariadb',
                           'prerequisites/cloud-databases/aliyun-rds-for-mongodb',
                           'prerequisites/cloud-databases/aliyun-rds-for-mysql',
                           'prerequisites/cloud-databases/aliyun-rds-for-pg',
                           'prerequisites/cloud-databases/amazon-rds-mysql',
                           'prerequisites/cloud-databases/huawei-cloud-gaussdb',
                           'prerequisites/cloud-databases/polardb-mysql',                           
                           'prerequisites/cloud-databases/polardb-postgresql',
                           'prerequisites/cloud-databases/tencentdb-for-mariadb',
                           'prerequisites/cloud-databases/tencentdb-for-mongodb',
                           'prerequisites/cloud-databases/tencentdb-for-pg',
                          ]
                   },
                  {
                   type: 'category',
                   label: '消息队列与中间件',
                   link: {type: 'doc', id: 'prerequisites/mq-and-middleware/README'},
                   items: [
                           'prerequisites/mq-and-middleware/activemq',
                           'prerequisites/mq-and-middleware/hazelcast-cloud',
                           'prerequisites/mq-and-middleware/kafka',
                           'prerequisites/mq-and-middleware/rabbitmq',
                           'prerequisites/mq-and-middleware/rocketmq',
                          ]
                   },
                   {
                    type: 'category',
                    label: 'SaaS 应用与 API 服务',
                    link: {type: 'doc', id: 'prerequisites/saas-and-api/README'},
                    items: [
                            'prerequisites/saas-and-api/coding',
                            'prerequisites/saas-and-api/quick-api',
                            'prerequisites/saas-and-api/vika',
                            'prerequisites/saas-and-api/zoho-desk',
                           ]
                   },
                   {
                    type: 'category',
                    label: '文件',
                    link: {type: 'doc', id: 'prerequisites/files/README'},
                    items: [
                            'prerequisites/files/csv',
                            'prerequisites/files/excel',
                            'prerequisites/files/json',
                            'prerequisites/files/xml',
                           ]
                   },
                   {
                    type: 'category',
                    label: '其他',
                    link: {type: 'doc', id: 'prerequisites/others/README'},
                    items: [
                            'prerequisites/others/custom-connection',
                            'prerequisites/others/dummy',
                            'prerequisites/others/http-receiver',
                            'prerequisites/others/mock-source',
                            'prerequisites/others/mock-target',
                           ]
                   },
         ]
    },
 ]
};

module.exports = sidebars;
